name: Backend Prod Build

on:
  push:
    branches: ["main"]
    paths:
      - "apps/backend/**"

  pull_request:
    branches: ["main"]
    paths:
      - "apps/backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./apps/backend
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/skywelltestdrivebackend:prod
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/skywelltestdrivebackend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/skywelltestdrivebackend:buildcache,mode=max
      - name: Call Webhook Endpoint
        run: curl -H 'Authorization:\ Bearer ${{ secrets.COOLIFY_AUTH_TOKEN }}' ${{ secrets.BACKEND_WEBHOOK_URL_PROD}}
